# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
    NCTU_OAUTH_KEY: HkrBkhvzPhOBzrjq90gEPfsw4uMbMVT9nQlEqq7U
    NCTU_OAUTH_SECRET_KEY: dTeq6QuMw7YlJgcPi7Fvd9XEcbyE8Nz1cMeX4C6ns74M2NTyNyvjaK7i8Fkc8tgvoICC1PCecPccxCyv1bC2vWy6JgA6oH2UY70qh1lPNFztqVflPJEZo75flZDy2oOM

development:
  secret_key_base: 2952ff7e97877f16c423863ed8c03505c6e03f98328cf00ebd3731b89aa43062fbb9df3180046aaa866531198707fd44060e23212296e89370dad39d8c95e8ea

test:
  secret_key_base: aa007800ae0f64fa4f804254fcd542d0c6801bdf2c488775ca58664f32d299e103127142e3c6c8c584312dda5bbb566d029ad79a72729cf78fb00b7278be5829
  
staging:
  secret_key_base: 9c398591847388a2e6039ad0848626f98f0172be212eb6cbc605d11b27d46e79b03264cf8e00af53fc949de7a57b92f4aa499eb2e3a80f7178307e16ef80fcc6


# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
